lbc:
    container_name: lbc-server
    ports:
        - 5006:5000
    volumes:
        - ../lbc/db.sqlite:/python-docker/db.sqlite
    build:
    context: ../lbc
    dockerfile: ../lbc/Dockerfile
    no_cache: true
    restart: unless-stopped
